class CfgPatches
{
	class DayZExpansion_Objects_BaseBuilding_Flags
	{
		requiredVersion=0.1;
		requiredAddons[]=
		{
			"DZ_Characters_Tops",
			"DZ_Gear_Camping"
		};
	};
};
class CfgVehicles
{
	class Armband_ColorBase;
	class Flag_Base;
	class Expansion_Flag_Expansion: Flag_Base
	{
		scope=2;
		color="Expansion_Expansion";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa"
		};
	};
	class Expansion_Flag_White: Flag_Base
	{
		scope=2;
		color="Expansion_White";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa"
		};
	};
	class Expansion_Flag_Australia: Flag_Base
	{
		scope=2;
		color="Expansion_Australia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa"
		};
	};
	class Expansion_Flag_Canada: Flag_Base
	{
		scope=2;
		color="Expansion_Canada";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa"
		};
	};
	class Expansion_Flag_Chernarus: Flag_Base
	{
		scope=2;
		color="Expansion_Chernarus";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa"
		};
	};
	class Expansion_Flag_France: Flag_Base
	{
		scope=2;
		color="Expansion_France";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa"
		};
	};
	class Expansion_Flag_Germany: Flag_Base
	{
		scope=2;
		color="Expansion_Germany";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa"
		};
	};
	class Expansion_Flag_Latvia: Flag_Base
	{
		scope=2;
		color="Expansion_Latvia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa"
		};
	};
	class Expansion_Flag_Luxembourg: Flag_Base
	{
		scope=2;
		color="Expansion_Luxembourg";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa"
		};
	};
	class Expansion_Flag_Mexico: Flag_Base
	{
		scope=2;
		color="Expansion_Mexico";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa"
		};
	};
	class Expansion_Flag_Netherlands: Flag_Base
	{
		scope=2;
		color="Expansion_Netherlands";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa"
		};
	};
	class Expansion_Flag_NewZealand: Flag_Base
	{
		scope=2;
		color="Expansion_NewZealand";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa"
		};
	};
	class Expansion_Flag_Norway: Flag_Base
	{
		scope=2;
		color="Expansion_Norway";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa"
		};
	};
	class Expansion_Flag_Poland: Flag_Base
	{
		scope=2;
		color="Expansion_Poland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa"
		};
	};
	class Expansion_Flag_Russia: Flag_Base
	{
		scope=2;
		color="Expansion_Russia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa"
		};
	};
	class Expansion_Flag_UK: Flag_Base
	{
		scope=2;
		color="Expansion_UK";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa"
		};
	};
	class Expansion_Flag_USA: Flag_Base
	{
		scope=2;
		color="Expansion_USA";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa"
		};
	};
	class Expansion_Flag_Scotland: Flag_Base
	{
		scope=2;
		color="Expansion_Scotland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa"
		};
	};
	class Expansion_Flag_Scottish: Expansion_Flag_Scotland
	{
	};
	class Expansion_Flag_Sweden: Flag_Base
	{
		scope=2;
		color="Expansion_Sweden";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa"
		};
	};
	class Expansion_Flag_Swedish: Expansion_Flag_Sweden
	{
	};
	class Expansion_Flag_Spain: Flag_Base
	{
		scope=2;
		color="Expansion_Spain";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa"
		};
	};
	class Expansion_Flag_Denmark: Flag_Base
	{
		scope=2;
		color="Expansion_Denmark";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa"
		};
	};
	class Expansion_Flag_Brazil: Flag_Base
	{
		scope=2;
		color="Expansion_Brazil";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa"
		};
	};
	class Expansion_Flag_Portugal: Flag_Base
	{
		scope=2;
		color="Expansion_Portugal";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa"
		};
	};
	class Expansion_Flag_Belgium: Flag_Base
	{
		scope=2;
		color="Expansion_Belgium";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa"
		};
	};
	class Expansion_Flag_Livonia: Flag_Base
	{
		scope=2;
		color="Expansion_Livonia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa"
		};
	};
	class Expansion_Flag_Japan: Flag_Base
	{
		scope=2;
		color="Expansion_Japan";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa"
		};
	};
	class Expansion_Flag_China: Flag_Base
	{
		scope=2;
		color="Expansion_China";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa"
		};
	};
	class Expansion_Flag_SouthKorea: Flag_Base
	{
		scope=2;
		color="Expansion_SouthKorea";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa"
		};
	};
	class Expansion_Flag_UN: Flag_Base
	{
		scope=2;
		color="Expansion_UN";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa"
		};
	};
	class Expansion_Flag_NATO: Flag_Base
	{
		scope=2;
		color="Expansion_NATO";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa"
		};
	};
	class Expansion_Flag_Pirate: Flag_Base
	{
		scope=2;
		color="Expansion_Pirate";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa"
		};
	};
	class Expansion_Flag_Chedaki: Flag_Base
	{
		scope=2;
		color="Expansion_Chedaki";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa"
		};
	};
	class Expansion_Flag_NAPA: Flag_Base
	{
		scope=2;
		color="Expansion_NAPA";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa"
		};
	};
	class Expansion_Flag_CDF: Flag_Base
	{
		scope=2;
		color="Expansion_CDF";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa"
		};
	};
	class Expansion_Flag_NuevoRico: Flag_Base
	{
		scope=2;
		color="Expansion_NuevoRico";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa"
		};
	};
	class Expansion_Flag_Borduria: Flag_Base
	{
		scope=2;
		color="Expansion_Borduria";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa"
		};
	};
	class Expansion_Flag_Borduriens: Expansion_Flag_Borduria
	{
	};
	class Expansion_Flag_Biohazard: Flag_Base
	{
		scope=2;
		color="Expansion_Biohazard";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa"
		};
	};
	class Expansion_Flag_AnyoneInCherno: Flag_Base
	{
		scope=2;
		color="Expansion_AnyoneInCherno";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa"
		};
	};
	class Expansion_Flag_Ireland: Flag_Base
	{
		scope=2;
		color="Expansion_Ireland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa"
		};
	};
	class Expansion_Flag_Italy: Flag_Base
	{
		scope=2;
		color="Expansion_Italy";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa"
		};
	};
	class Expansion_Flag_Irish: Expansion_Flag_Ireland
	{
	};
	class Expansion_Flag_Wales: Flag_Base
	{
		scope=2;
		color="Expansion_Wales";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa"
		};
	};
	class Expansion_Flag_Switzerland: Flag_Base
	{
		scope=2;
		color="Expansion_Switzerland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa"
		};
	};
	class Expansion_Flag_SriLanka: Flag_Base
	{
		scope=2;
		color="Expansion_SriLanka";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa"
		};
	};
	class Expansion_Flag_Skilanka: Expansion_Flag_SriLanka
	{
	};
	class Expansion_Flag_SouthAfrica: Flag_Base
	{
		scope=2;
		color="Expansion_SouthAfrica";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa"
		};
	};
	class Expansion_Flag_Sicily: Flag_Base
	{
		scope=2;
		color="Expansion_Sicily";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa"
		};
	};
	class Expansion_Flag_OffWithHead: Flag_Base
	{
		scope=2;
		color="Expansion_OffWithHead";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa"
		};
	};
	class Expansion_Flag_Gibraltar: Flag_Base
	{
		scope=2;
		color="Expansion_Gibraltar";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa"
		};
	};
	class Expansion_Flag_Gubraltar: Expansion_Flag_Gibraltar
	{
	};
	class Expansion_Flag_Czechia: Flag_Base
	{
		scope=2;
		color="Expansion_Czechia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa"
		};
	};
	class Expansion_Flag_Czech: Expansion_Flag_Czechia
	{
	};
	class Expansion_Flag_Fari: Flag_Base
	{
		scope=2;
		color="Expansion_Fari";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa"
		};
	};
	class Expansion_Flag_Finland: Flag_Base
	{
		scope=2;
		color="Expansion_Finland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa"
		};
	};
	class Expansion_Flag_Finnish: Expansion_Flag_Finland
	{
	};
	class Expansion_Flag_Argentina: Flag_Base
	{
		scope=2;
		color="Expansion_Argentina";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa"
		};
	};
	class Expansion_Flag_Turkey: Flag_Base
	{
		scope=2;
		color="Expansion_Turkey";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa"
		};
	};
	class Expansion_Flag_Ukraine: Flag_Base
	{
		scope=2;
		color="Expansion_Ukraine";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa"
		};
	};
	class Expansion_Flag_DayZWhite: Flag_Base
	{
		scope=2;
		color="Expansion_DayZWhite";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa"
		};
	};
	class Expansion_Flag_DayZBlack: Flag_Base
	{
		scope=2;
		color="Expansion_DayZBlack";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa"
		};
	};
	class Expansion_Flag_DoubleAxe: Flag_Base
	{
		scope=2;
		color="Expansion_DoubleAxe";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa"
		};
	};
	class Expansion_Flag_Grenade: Flag_Base
	{
		scope=2;
		color="Expansion_Grenade";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa"
		};
	};
	class Expansion_Flag_Red: Flag_Base
	{
		scope=2;
		color="Expansion_Red";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa"
		};
	};
	class Expansion_Flag_Blue: Flag_Base
	{
		scope=2;
		color="Expansion_Blue";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa"
		};
	};
	class Expansion_Flag_Green: Flag_Base
	{
		scope=2;
		color="Expansion_Green";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa"
		};
	};
	class Expansion_Flag_Yellow: Flag_Base
	{
		scope=2;
		color="Expansion_Yellow";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa"
		};
	};
	class Expansion_Flag_Orange: Flag_Base
	{
		scope=2;
		color="Expansion_Orange";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa"
		};
	};
	class Expansion_Flag_Pink: Flag_Base
	{
		scope=2;
		color="Expansion_Pink";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa"
		};
	};
	class Expansion_Flag_Purple: Flag_Base
	{
		scope=2;
		color="Expansion_Purple";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa"
		};
	};
	class Expansion_Flag_Rainbow: Flag_Base
	{
		scope=2;
		color="Expansion_Rainbow";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa"
		};
	};
	class Armband_Expansion_Expansion: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Expansion";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_expansion_co.paa"
		};
	};
	class Armband_Expansion_White: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_White";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_white_co.paa"
		};
	};
	class Armband_Expansion_Australia: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Australia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_australia_co.paa"
		};
	};
	class Armband_Expansion_Canada: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Canada";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_canada_co.paa"
		};
	};
	class Armband_Expansion_Chernarus: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Chernarus";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chernarus_co.paa"
		};
	};
	class Armband_Expansion_France: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_France";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_france_co.paa"
		};
	};
	class Armband_Expansion_Germany: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Germany";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_germany_co.paa"
		};
	};
	class Armband_Expansion_Latvia: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Latvia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_latvia_co.paa"
		};
	};
	class Armband_Expansion_Luxembourg: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Luxembourg";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_luxembourg_co.paa"
		};
	};
	class Armband_Expansion_Mexico: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Mexico";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_mexico_co.paa"
		};
	};
	class Armband_Expansion_Netherlands: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Netherlands";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_netherlands_co.paa"
		};
	};
	class Armband_Expansion_NewZealand: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_NewZealand";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_new_zealand_co.paa"
		};
	};
	class Armband_Expansion_Norway: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Norway";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_norway_co.paa"
		};
	};
	class Armband_Expansion_Poland: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Poland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_poland_co.paa"
		};
	};
	class Armband_Expansion_Russia: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Russia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_russia_co.paa"
		};
	};
	class Armband_Expansion_UK: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_UK";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_uk_co.paa"
		};
	};
	class Armband_Expansion_USA: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_USA";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_usa_co.paa"
		};
	};
	class Armband_Expansion_Scotland: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Scotland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_scotland_co.paa"
		};
	};
	class Armband_Expansion_Scottish: Expansion_Flag_Scotland
	{
	};
	class Armband_Expansion_Sweden: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Sweden";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sweden_co.paa"
		};
	};
	class Armband_Expansion_Swedish: Expansion_Flag_Sweden
	{
	};
	class Armband_Expansion_Spain: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Spain";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_spain_co.paa"
		};
	};
	class Armband_Expansion_Denmark: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Denmark";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_denmark_co.paa"
		};
	};
	class Armband_Expansion_Brazil: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Brazil";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_brazil_co.paa"
		};
	};
	class Armband_Expansion_Portugal: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Portugal";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_portugal_co.paa"
		};
	};
	class Armband_Expansion_Belgium: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Belgium";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_belgium_co.paa"
		};
	};
	class Armband_Expansion_Livonia: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Livonia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_livonia_co.paa"
		};
	};
	class Armband_Expansion_Japan: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Japan";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_japan_co.paa"
		};
	};
	class Armband_Expansion_China: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_China";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_china_co.paa"
		};
	};
	class Armband_Expansion_SouthKorea: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_SouthKorea";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southkorea_co.paa"
		};
	};
	class Armband_Expansion_UN: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_UN";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_un_co.paa"
		};
	};
	class Armband_Expansion_NATO: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_NATO";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nato_co.paa"
		};
	};
	class Armband_Expansion_Pirate: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Pirate";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_pirate_co.paa"
		};
	};
	class Armband_Expansion_Chedaki: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Chedaki";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_chedaki_co.paa"
		};
	};
	class Armband_Expansion_NAPA: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_NAPA";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_napa_co.paa"
		};
	};
	class Armband_Expansion_CDF: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_CDF";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_cdf_co.paa"
		};
	};
	class Armband_Expansion_NuevoRico: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_NuevoRico";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_nuevorico_co.paa"
		};
	};
	class Armband_Expansion_Borduria: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Borduria";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_borduria_co.paa"
		};
	};
	class Armband_Expansion_Borduriens: Expansion_Flag_Borduria
	{
	};
	class Armband_Expansion_Biohazard: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Biohazard";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_biohazard_co.paa"
		};
	};
	class Armband_Expansion_AnyoneInCherno: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_AnyoneInCherno";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_anyoneincherno_co.paa"
		};
	};
	class Armband_Expansion_Ireland: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Ireland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ireland_co.paa"
		};
	};
	class Armband_Expansion_Italy: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Italy";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_italy_co.paa"
		};
	};
	class Armband_Expansion_Irish: Expansion_Flag_Ireland
	{
	};
	class Armband_Expansion_Wales: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Wales";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_wales_co.paa"
		};
	};
	class Armband_Expansion_Switzerland: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Switzerland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_switzerland_co.paa"
		};
	};
	class Armband_Expansion_SriLanka: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_SriLanka";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_srilanka_co.paa"
		};
	};
	class Armband_Expansion_Skilanka: Expansion_Flag_SriLanka
	{
	};
	class Armband_Expansion_SouthAfrica: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_SouthAfrica";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_southafrica_co.paa"
		};
	};
	class Armband_Expansion_Sicily: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Sicily";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_sicily_co.paa"
		};
	};
	class Armband_Expansion_OffWithHead: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_OffWithHead";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_offwithhead_co.paa"
		};
	};
	class Armband_Expansion_Gibraltar: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Gibraltar";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_gibraltar_co.paa"
		};
	};
	class Armband_Expansion_Gubraltar: Expansion_Flag_Gibraltar
	{
	};
	class Armband_Expansion_Czechia: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Czechia";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_czechia_co.paa"
		};
	};
	class Armband_Expansion_Czech: Expansion_Flag_Czechia
	{
	};
	class Armband_Expansion_Fari: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Fari";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_fari_co.paa"
		};
	};
	class Armband_Expansion_Finland: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Finland";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_finland_co.paa"
		};
	};
	class Armband_Expansion_Finnish: Expansion_Flag_Finland
	{
	};
	class Armband_Expansion_Argentina: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Argentina";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_argentina_co.paa"
		};
	};
	class Armband_Expansion_Turkey: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Turkey";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_turkey_co.paa"
		};
	};
	class Armband_Expansion_Ukraine: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Ukraine";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\countries\flag_ukraine_co.paa"
		};
	};
	class Armband_Expansion_DayZWhite: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_DayZWhite";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzwhite_co.paa"
		};
	};
	class Armband_Expansion_DayZBlack: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_DayZBlack";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_dayzblack_co.paa"
		};
	};
	class Armband_Expansion_DoubleAxe: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_DoubleAxe";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_doubleaxe_co.paa"
		};
	};
	class Armband_Expansion_Grenade: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Grenade";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\logos\flag_grenade_co.paa"
		};
	};
	class Armband_Expansion_Red: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Red";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_red_co.paa"
		};
	};
	class Armband_Expansion_Blue: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Blue";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_blue_co.paa"
		};
	};
	class Armband_Expansion_Green: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Green";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_green_co.paa"
		};
	};
	class Armband_Expansion_Yellow: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Yellow";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_yellow_co.paa"
		};
	};
	class Armband_Expansion_Orange: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Orange";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_orange_co.paa"
		};
	};
	class Armband_Expansion_Pink: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Pink";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_pink_co.paa"
		};
	};
	class Armband_Expansion_Purple: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Purple";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_purple_co.paa"
		};
	};
	class Armband_Expansion_Rainbow: Armband_ColorBase
	{
		scope=2;
		visibilityModifier=0.94999999;
		color="Expansion_Rainbow";
		hiddenSelectionsTextures[]=
		{
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa",
			"\DayZExpansion\Objects\Structures\Flags\data\colors\flag_rainbow_co.paa"
		};
	};
};
