enum eAICommands
{
	// Movement
	MOV_STOP,
	MOV_GOTO,
	MOV_RTF, // Return to formation
	MOV_GETIN,
	MOV_SETWP,
	MOV_CLEARWP,
	// Formation 
	FOR_VEE,
	FOR_INVVEE,
	FOR_FILE,
	FOR_INVFILE,
	FOR_WALL,
	FOR_COL,
	FOR_INVCOL,
	FOR_CIRCLE,
	FOR_CIRCLEDOT,
	FOR_STAR,
	FOR_STARDOT,
	// Status
	STA_SITREP, // report health and ammo level
	STA_POSITION, // report position
	STA_THREATS,
	STA_DUMP,
	STA_UNUSED,
	// Debug
	DEB_SPAWNALLY,
	DEB_SPAWNSENTRY,
	DEB_SPAWNGUARD,
	DEB_SPAWNPASSIVE,
	DEB_SPAWNSHAMAN,
	DEB_SPAWNZOM,
	DEB_SPAWNWOLF,
	DEB_SPAWNBEAR,
	DEB_CLEARALL,
	DEB_AIMAP, // TODO
	DEB_GRPMGR, // TODO
	DEB_TARGET_CREATE,
	DEB_TARGET_DESTROY,
	DEB_EXPORTPATROL,
};
