enum eAICommands
{
	DEB_DAMAGE,
	DEB_DAMAGE_COUNT = 20,
	// Movement
	MOV_STOP,
	MOV_FLANK,
	MOV_ROAM,
	MOV_GOTO,
	MOV_RTF, // Return to formation
	MOV_GETIN,
	MOV_SETWP,
	MOV_CLEARWP,
	MOV_WALK,
	MOV_JOG,
	MOV_SPRINT,
	MOV_ERECT,
	MOV_CROUCH,
	MOV_PRONE,
	// Formation 
	FOR_VEE,
	FOR_INVVEE,
	FOR_FILE,
	FOR_INVFILE,
	FOR_WALL,
	FOR_COL,
	FOR_INVCOL,
	FOR_CIRCLE,
	FOR_CIRCLEDOT,
	FOR_STAR,
	FOR_STARDOT,
	FOR_SCALE_1X,
	FOR_SCALE_2X,
	FOR_SCALE_3X,
	FOR_SCALE_4X,
	FOR_SCALE_5X,
	FOR_LOOSENESS_00,
	FOR_LOOSENESS_05,
	FOR_LOOSENESS_10,
	FOR_LOOSENESS_15,
	FOR_LOOSENESS_20,
	FOR_LOOSENESS_30,
	FOR_LOOSENESS_40,
	FOR_LOOSENESS_50,
	// Status
	STA_SITREP, // report health and ammo level
	STA_POSITION, // report position
	STA_THREATS,
	STA_DUMP,
	STA_UNUSED,
	// Debug
	DEB_SPAWNALLY,
	DEB_SPAWNZOM,
	DEB_SPAWNWOLF,
	DEB_SPAWNBEAR,
	DEB_CLEARALL,
	DEB_AIMAP, // TODO
	DEB_GRPMGR, // TODO
	DEB_TARGET_CREATE,
	DEB_TARGET_DESTROY,
	DEB_EXPORTPATROL,
	DEB_UNLIMITEDRELOAD_ALL,
	DEB_UNLIMITEDRELOAD_ANIMALS,
	DEB_UNLIMITEDRELOAD_INFECTED,
	DEB_UNLIMITEDRELOAD_PLAYERS,
	DEB_UNLIMITEDRELOAD_VEHICLES,
	DEB_DBGOBJECTS,
	DEB_DBGDAMAGE,
	DEB_RESET_PATHFINDING,
	DEB_FORCEWEAPONRESYNC,
	DEB_SPECTATE,
	// Behaviour
	BEH_LOOT  //! Always keep BEH_LOOT as the last entry!
};

enum eAICommandCategories
{
	CATEGORIES,	//special category selection
	CAT_MOVEMENT,
	CAT_MOVEMENT_SPEED,
	CAT_MOVEMENT_STANCE,
	CAT_FORMATION,
	CAT_FORMATION_SCALE,
	CAT_FORMATION_LOOSENESS,
	CAT_STATUS,
	CAT_DEBUG,
	CAT_FACTION,
	CAT_SPAWNFACTION,
	CAT_LOOTINGBEHAVIOUR,
	CAT_LOOTINGBEHAVIOUR_CLOTHING_BACK,
	CAT_UNLIMITEDRELOAD,
	CAT_DAMAGE_IN,
	CAT_DAMAGE_OUT,
	CAT_HEADSHOTRESISTANCE,
	CAT_EMPTY
};
