enum eAIWaypointBehavior
{
	HALT,
	LOOP,
	ALTERNATE,
	ONCE,
	HALT_OR_LOOP,
	HALT_OR_ALTERNATE,
	ROAMING,
	MIXED  //! TODO
};

enum eAILootingBehavior
{
	NONE = 0,
	WEAPONS_FIREARMS = 1,
	WEAPONS_LAUNCHERS = 2,
	WEAPONS_MELEE = 4,
	WEAPONS = 7,  //! WEAPONS_FIREARMS | WEAPONS_LAUNCHERS | WEAPONS_MELEE
	BANDAGES = 8,
	CLOTHING_ARMBAND = 16,
	CLOTHING_BACK_LARGE = 32,
	CLOTHING_BACK_MEDIUM = 64,
	CLOTHING_BACK_SMALL = 128,
	CLOTHING_BODY = 256,
	CLOTHING_EYEWEAR = 512,
	CLOTHING_FEET = 1024,
	CLOTHING_GLOVES = 2048,
	CLOTHING_HEADGEAR = 4096,
	CLOTHING_HIPS = 8192,
	CLOTHING_LEGS = 16384,
	CLOTHING_MASK = 32768,
	CLOTHING_MELEE = 65536,
	CLOTHING_SHOULDER = 131072,
	CLOTHING_VEST = 262144,
	CLOTHING = 524272,
	UPGRADE = 524288,
	DEFAULT = 7,  //! WEAPONS_FIREARMS | WEAPONS_LAUNCHERS | WEAPONS_MELEE
	ALL = 1048575  //! WEAPONS | BANDAGES | CLOTHING | UPGRADE
};

enum eAIGroupFormationState
{
	NONE,
	IN,
	FLANK
};

enum eAIMovementSpeed
{
	STATIC,
	WALK,
	JOG,
	SPRINT,
	RANDOM,
	RANDOM_NONSTATIC
};

enum eAITargetType
{
	NONE = 0,
	ALL = 1,
	ANIMAL = 2,
	INFECTED = 4,
	PLAYER = 8,
	VEHICLE = 16,
	ALL_OR = 30  //! ANIMAL | INFECTED | PLAYER | VEHICLE
};
