#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\ObjectEditor.c"

#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\gui\\EditorMenu.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\gui\\ObjectMenu.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\gui\\MatMenu.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\gui\\PositionMenu.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\gui\\WeatherMenu.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\gui\\GameMenu.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\gui\\PopupMenu.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\gui\\ObjectInfoMenu.c"

#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\scene\\Scene.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\scene\\SceneManager.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\scene\\SceneInfo.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\scene\\ObjectData.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\scene\\LootSpot.c"
#include "$CurrentDir:missions\\ExpansionCOM.ChernarusPlus\\core\\modules\\ComEditor\\scene\\SceneSaveST.c"